#!/bin/bash

printf "Installing linux-tools... "
sudo apt-get -qq install linux-tools-generic linux-tools-common linux-tools-`uname -r`
printf "Done.\n"

printf "Changing sudoers file... "
echo 'Defaults env_keep += "PYTHONPATH"' | sudo EDITOR='tee -a' visudo
printf "Done.\n"

printf "Installing pip... "
python3 -mpip install -U pip
printf "Done.\n"

printf "Installing numpy, matplotlib... "
sudo apt-get -qq install python3-tk
python3 -mpip install -U numpy matplotlib
printf "Done.\n"

printf "Installing IPython... "
pip install ipython
printf "Done.\n"

printf "Installing pandas... "
pip install pandas
printf "Done.\n"

