#!/usr/bin/end python3
# -----------------------------------------------------------------------------
# runner - Runs collect UT.
#
# July 2018, Matt Ware
#
# -----------------------------------------------------------------------------

"""Runs Collect UT"""


import os
import sys
import unittest

this_dir = os.path.dirname(os.path.realpath(__file__))
leap_dir = os.path.dirname(os.path.dirname(this_dir))

try:
    import collect
except ImportError:
    # Try to manipulate the pythonpath
    sys.path.append(leap_dir)
    import collect.test


# Run all tests beneath this directory.
all_tests = unittest.TestLoader().discover(str(this_dir), pattern="*.py")
unittest.TextTestRunner().run(all_tests)

